---
    - name: restart Grafana
      service:
        name: grafana-server
        state: restarted
        enabled: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted
