global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'local-node'
    static_configs:
      - targets:
          - localhost:9100
        labels:
          env: "local"
          service: "node"

  - job_name: 'local-prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: "local"
          service: "prometheus"

  - job_name: 'local-alertmanager'
    static_configs:
      - targets: ['localhost:9093']
        labels:
          env: "local"
          service: "alertmanager"

